#include <iostream>
#include <string>
#include <algorithm>

/**
 * @brief You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
 * 
 */

class Solution {
public:
    char findTheDifference(std::string s, std::string t) {
        std::sort(s.begin(), s.end());
        std::sort(t.begin(), t.end());

        for(size_t i = 0; i < s.length(); i++) {
            char c = s[i];
            if(s[i] != t[i]) {
                return t[i];
            }
        }

        return t[t.size() - 1];
    }
};

int main(void) {
    Solution solution;
    std::string s = "abcd";
    std::string t = "abcde";
    std::cout << solution.findTheDifference(s, t) << std::endl;
    return 0;
}